[package]
name = "lap_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.96", features = ["extra-traits", "full"] }
quote = "1.0.18"
proc-macro2 = "1.0.40"
